USE [master]
GO

/****** Object:  Database [DWGlobalSales]    Script Date: 9/8/2025 22:50:32 ******/
CREATE DATABASE [DWGlobalSales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWGlobalSales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\DWGlobalSales.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DWGlobalSales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\DWGlobalSales_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWGlobalSales].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DWGlobalSales] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DWGlobalSales] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DWGlobalSales] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DWGlobalSales] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DWGlobalSales] SET ARITHABORT OFF 
GO

ALTER DATABASE [DWGlobalSales] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DWGlobalSales] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DWGlobalSales] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DWGlobalSales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DWGlobalSales] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DWGlobalSales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DWGlobalSales] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DWGlobalSales] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DWGlobalSales] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DWGlobalSales] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DWGlobalSales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DWGlobalSales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DWGlobalSales] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DWGlobalSales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DWGlobalSales] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DWGlobalSales] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DWGlobalSales] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DWGlobalSales] SET RECOVERY FULL 
GO

ALTER DATABASE [DWGlobalSales] SET  MULTI_USER 
GO

ALTER DATABASE [DWGlobalSales] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DWGlobalSales] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DWGlobalSales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DWGlobalSales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DWGlobalSales] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DWGlobalSales] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DWGlobalSales] SET QUERY_STORE = ON
GO

ALTER DATABASE [DWGlobalSales] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DWGlobalSales] SET  READ_WRITE 
GO


